### PR TITLE
F fix deprecated call

### LINKED ISSUE #58: Fix deprecated call
in sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp

pluginlib::ClassLoader<T>::createClassInstance

is deprecated
should now be using 

pluginlib::ClassLoader<T>::createInstance

It returns a boost::shared_ptr instead of a normal pointer.

### PR DESCRIPTION
**Pull request by shadowmanos**
closed #58

### CODE REVIEW

File: sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp [hunk 1]
```diff
@@ -74,7 +74,7 @@
       //ROS_WARN("Using driver class '%s' for device with product code %d",
       //         matching_class_name.c_str(), product_code);
       try {
-        cod_decod_ = boost::shared_ptr<CodDecod>(cod_decod_loader_.createClassInstance(matching_class_name));
+        cod_decod_ = boost::shared_ptr<CodDecod>(cod_decod_loader_.createInstance( matching_class_name ) );
```
Comment (toliver) [inline sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp]: in this case you should not create a boost::shared_pointer, as the function createInstance already returns one.
It should be 
cod_decod_ =cod_decod_loader_.createInstance( matching_class_name ) ;

File: sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp [hunk 2]
```diff
@@ -95,7 +95,7 @@
       }
       ROS_INFO("Loading the deafult CodDecod plugin: CodDecodStdIo");
       try {
-        cod_decod_ = boost::shared_ptr<CodDecod>(cod_decod_loader_.createClassInstance("sr_ronex_drivers/87032868_0"));
+        cod_decod_ = boost::shared_ptr<CodDecod>(cod_decod_loader_.createInstance("sr_ronex_drivers/87032868_0"));
```
Comment (toliver) [inline sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp]: same

File: sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp [hunk 3]
```diff
@@ -93,9 +93,9 @@
       {
         ROS_INFO("  %s", class_name.c_str());
       }
-      ROS_INFO("Loading the deafult CodDecod plugin: CodDecodStdIo");
+      ROS_INFO("Loading the default CodDecod plugin: CodDecodStdIo");
```
Comment (toliver) [inline sr_ronex_drivers/src/cod_decod/cod_decod_manager.cpp:96]: Well spotted!!
